version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0
    commands:
      - echo Installing Lambda Tools
      - dotnet tool install -g Amazon.Lambda.Tools
      - export PATH="$PATH:/root/.dotnet/tools"
      - cd Backend/TechWorldAPI
      - dotnet restore

  build:
    commands:
      - echo Packaging Lambda...
      - dotnet lambda package --configuration Release --framework net8.0 --output-package deployment.zip
      - aws s3 cp deployment.zip s3://tech-world-backend-artifacts/deployment.zip

artifacts:
  files:
    - Backend/TechWorldAPI/serverless.template
