version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install -g @angular/cli

  pre_build:
    commands:
      - cd Frontend
      - npm install

  build:
    commands:
      - ng build --configuration production

  post_build:
    commands:
      cd dist
      - echo "Going to Folder"
      - echo "Uploading to S3..."
      - aws s3 sync dist/ s3://tech-world-frontend/ --delete
      - echo "Invalidating CloudFront..."
      - aws cloudfront create-invalidation --distribution-id E3FTJDQOOT2OHZ --paths "/*"

artifacts:
  files:
    - '**/*'
  base-directory: Frontend/dist
