version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20   # choose your Node version
    commands:
      - echo Installing Angular CLI
      - npm install -g @angular/cli
  pre_build:
    commands:
      - echo Installing frontend dependencies
      - cd Frontend
      - npm install
  build:
    commands:
      - echo Building Angular frontend
      - ng build --configuration production

artifacts:
  files:
    - '**/*'
  base-directory: Frontend/dist
